### ISSUE TITLE
Live execution output

### ISSUE THREAD

**Issue by Grinderofl** [SharpeRAD/Cake.Powershell#13]
It appears that currently the script is executed, and nothing happens until the execution is complete, after which the entire output is displayed at once. Could this be changed, or a feature added, so that it would show output as it happens? If there's a long-running script, I would like to be able to see the output live.

**Comment by SharpeRAD** [comment]
That was the original intention for this addin but I gave up on it after a few unfruitful days 😞 More than happy to accept a PR for this though if your up for the challenge 😉

**Comment by yanigisawa** [comment]
I believe I have a working solution for this. I will submit a PR for your review.

**Comment by SharpeRAD** [comment]
Closing this now as @yanigisawa solved this with #23 👍
