### ISSUE TITLE
Use modules in powershell is not working

### ISSUE THREAD

**Issue by franreyes** [SharpeRAD/Cake.Powershell#14]
When Module is loaded show this error:

> The specified module 'System.Collections.Generic.List1[System.String]' was not loaded because no valid module file was found in any module directory.

I think that problem is this line in PowershellRunner:

`pipeline.Commands.AddScript("Import-Module " + settings.Modules);`

Should be like this:
```
settings.Modules.ToList()
      .ForEach(m => pipeline.Commands.AddScript("Import-Module " + m));
```

**Comment by SharpeRAD** [comment]
Good catch, publishing a fix now 👍
