### ISSUE TITLE
StartPowershellScript runs script twice?

### ISSUE THREAD

**Issue by saasen** [SharpeRAD/Cake.Powershell#15]
Hi.

We're experiencing an issue where our powershell scripts are running twice. This is happening when using both these signatures:
* `public static Collection<PSObject> StartPowershellScript(this ICakeContext context, string script, Action<ProcessArgumentBuilder> arguments)`
* `public static Collection<PSObject> StartPowershellScript(this ICakeContext context, string script)`

Are you having this issue also? Here's our cake task:

```
Task(Task2)
  .IsDependentOn(Task1)
  .Does(() => {
        Information("Starting Powershell script.");
        StartPowershellScript($"./test.ps1", args =>
        {
            args.Append("baseUrl", parameters.BaseUrl);
            args.Append("version", parameters.Version.SemVersion);
            args.Append("branch",  parameters.Branch);
        });
  });
```

**Comment by saasen** [comment]
*UPDATE*: I played around with the versions of this addin, and the first version it began running the script twice is `v0.2.3`.

**Comment by saasen** [comment]
@SharpeRAD?

**Comment by SharpeRAD** [comment]
Sorry but no, scripts and files are only executed once. I've updated the test files to highlight this point. 

Run "./test/build.bat" for clarity.
