### ISSUE TITLE
How to detect a successful run?

### ISSUE THREAD

**Issue by avishnyakov** [SharpeRAD/Cake.Powershell#17]
Hey, great additon to Cakebuild. Using it with Pester post-build regression, completely love it.

However, not too sure on how to detect a successful outcome of StartPowershellFile(). Docs say it returns an array of PSObject, so.. what would be the easiest way to detect if StartPowershellFile had an exception or something?

**Comment by DixonDs** [comment]
I have a similar question regarding `StartPowershellScript`. I see the following line in the console output which says that an error occurred:
```
Exception of type 'System.Exception' was thrown
```
But the build is not failed. I would like to have the build failed in this case and also print exception details.

**Comment by SharpeRAD** [comment]
Alter your Powershell script to return a custom value, parse the PsObject in Cake and throw an exception in Cake based on its value.

Found a link on [StackOverflow ](http://stackoverflow.com/questions/10106217/how-would-i-return-an-object-or-multiple-values-from-powershell-to-executing-c-s) that will give you a starting point. If you get it working can you add it to the [example](https://github.com/SharpeRAD/Cake.Powershell/blob/master/test/build.cake) script for others to follow.
