### ISSUE TITLE
Adding .SetFormatOutput() to Settings will break any return codes from called script.

### ISSUE THREAD

**Issue by deekob** [SharpeRAD/Cake.Powershell#29]
There seems to have been a regression - as the Task("Failing-Powershell-File")  example in the test package does not work as expected.
The Test is this
 `Task("Failing-Powershell-File")
    .Description("An example showing how to handle errors from Powershell scripts")
    .Does(() =>
    {
        Information("Calling failing Powershell File");

        var resultCollection = StartPowershellFile("./failingScript.ps1", new PowershellSettings()
            **.SetFormatOutput()**
            .SetLogOutput());

        var returnCode = int.Parse(resultCollection[0].BaseObject.ToString());
        if (returnCode != 0) {
            throw new ApplicationException("Script failed to execute");
        }
    });`

This will now not work as expected until you remove the .SetFormatOutput() PowerShellSetting.  This is consistent to what we have been experiencing.

Also of note is that the Task above  is not actually wired into anything  and will only run as a custom target - I dont think that is expected.

**Comment by SharpeRAD** [comment]
Hopefully [this is clearer](https://github.com/SharpeRAD/Cake.Powershell/blob/master/test/build.cake)?
