### ISSUE TITLE
Failed to install addin

### ISSUE THREAD

**Issue by osc-solutions** [SharpeRAD/Cake.Powershell#39]
Does `Cake` know how to install an addin without the directory `lib\net45`? After the change
```
  <files>
      <file src="net461/System.Management.Automation.dll" target="lib/net461" />
      <file src="net461/Cake.Powershell.dll" target="lib/net461" />
      <file src="net461/Cake.Powershell.xml" target="lib/net461" />
      <file src="LICENSE" />
   </files>
```
I am getting 
```
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Powershell'.
```
I know its currently looking for `lib\net45`.
Does `Cake v0.22.2` use `net461`?

**Comment by SharpeRAD** [comment]
This made me panic, almost reissue a new version and be late for work 😠

You can't be using v0.22.0 or v0.22.2 as that uses net461.

Run the build.bat from the test folder, with no tools directory. It will create a clean install of cake and pull in the latest Cake.Powershell package which runs fine. You can even repeat the process with v0.22.0 or v0.22.2 by editing the build.sp1 file.
