### ISSUE TITLE
Cake.Powershell v0.4.0 not compatible with Cake v0.21.1

### ISSUE THREAD

**Issue by alexfrere** [SharpeRAD/Cake.Powershell#40]
It appears that Cake dlls using .NET v4.5 (i.e. in Cake v0.21.1) are not supported after targeting .NET v4.61 as part of commit a207a0c0d99b854df162edd12a1b02fba80e8eb7.

Error reported in PS when running default task that uses #addin "Cake.Powershell" is:

```
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing addins...
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Powershell'.
```

A temporary workaround is to explicitly target v0.3.5 e.g. #addin `"Cake.Powershell&version=0.3.5"` .

We need to pin to Cake v0.21.1 due to other addins not yet supporting v0.22.0 so we cannot use Cake.Powershell v0.4.0 at this stage.

**Comment by SharpeRAD** [comment]
Correct the **solution** is to pin Cake.Powershell to a lower version. No need to create an issue about that though 😜

**Comment by alexfrere** [comment]
Cheers for the fast response!

**Comment by SharpeRAD** [comment]
Had a second tab open at the time. 

Breaking changes are never cool but I didn't create them, I'm just trying to keep up with Cake 😉 

net461 makes sense if you look at the compatibility matrix for net standard, so I can't blame them for upgrading it as arguably everyone that was on net45 should be able to install net461.
