### ISSUE TITLE
Failed to install addin 'Cake.Powershell'

### ISSUE THREAD

**Issue by pyrochlore** [SharpeRAD/Cake.Powershell#41]
Hi, 
I got the error message while building target with directive #addin "Cake.Powershell".
Error: Failed to install addin 'Cake.Powershell'
Could not find any assemblies compatible with .NETFramework, Version=4.5

Any idea about this?

p.s.
My OS: Windows10 64
Powershell version 5.1

**Comment by SharpeRAD** [comment]
Upgrade to Cake v0.22.0 or pin to a lower version.
