### ISSUE TITLE
Failed to install addin 'Cake.Powershell'

### ISSUE THREAD

**Issue by AlbertoMonteiro** [SharpeRAD/Cake.Powershell#42]
I was using Cake.Powershell version 0.3.5 with Cake 0.19.5, now when using 0.4.0 with same Cake version I get this error: 
```
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Powershell'.
```

**Comment by dennisroche** [comment]
Unless configured, the Cake preprocessor will always download the latest version of any `#addin` or `#tool`. 

With packages updating to support Cake `0.22.0`  

A workaround for now is pin the version of the tools e.g. `#addin "nuget:?package=Cake.Powershell&version=0.3.5"`

To avoid random breakages for your build script, I would recommend pinning the version of all dependencies.

**Comment by SharpeRAD** [comment]
Thanks @dennisroche 👍

I've added a description to the [ReadMe](https://github.com/SharpeRAD/Cake.Powershell) and to the [Troubleshooting](https://github.com/SharpeRAD/Cake.Powershell/blob/master/TroubleShooting.md) page to explain Cakes changes. 

I'm also going to leave this issue open for a couple of weeks as I've closed 3 identical issues in the last day and I suspect there will be more to come 😢

**Comment by Dalmirog** [comment]
Thanks @dennisroche ! And also thanks @SharpeRAD for leaving this issue open making it easier for me to find it :)

**Comment by SharpeRAD** [comment]
Closing this now as I think its been long enough that people should be aware of the changes to Cake.
