### ISSUE TITLE
AppendQuoted example takes one argument

### ISSUE THREAD

**Issue by Scott-Lyons** [SharpeRAD/Cake.Powershell#44]
In the ReadMe.md the example of AppendQuoted only takes one argument but looking at src/Cake.Powershell/Extensions/ProcessArgumentListExtensions.cs two arguments are required.

**Comment by SharpeRAD** [comment]
I added helper methods to Cake.Powershell to work with named arguments but Cake.Core also has its own [extension methods](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs)
