### ISSUE TITLE
Could not load Microsoft.PowerShell.PackageManagement.dll (missing Microsoft.PackageManagement) when LoadDependencies option enabled

### ISSUE THREAD

**Issue by sean-rose** [SharpeRAD/Cake.Powershell#52]
Using the latest Cake.Powershell v0.4.4 with Cake v0.26.1 on Windows 10 x64 I got the following alert when running the script:

    Could not load C:\...\tools\Addins\Microsoft.PowerShell.5.ReferenceAssemblies.1.1.0\lib\net4\Microsoft.PowerShell.PackageManagement.dll (missing Microsoft.PackageManagement, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)

After downgrading to Cake.Powershell v0.4.3 and Cake v0.25.0 I don't get that alert.

**Comment by sean-rose** [comment]
After further testing, it appears this was probably caused by having Cake's `LoadDependencies` option enabled, causing it to download the dependent [Microsoft.PowerShell.5.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/) package and use the assemblies it contains, which are not strongly signed.

If so, it might be a good idea to add a note about that in the troubleshooting docs.

**Comment by sean-rose** [comment]
Come to think of it, the [Microsoft.PowerShell.5.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/) package seems like it's a development-only dependency, so that dependency could be removed from the generated [Cake.Powershell](https://www.nuget.org/packages/Cake.Powershell) package to avoid the possibility of this problem occurring altogether.

**Comment by SharpeRAD** [comment]
Should be resolved in v0.4.5
