### ISSUE TITLE
Issue Referencing Cake.Powershell

### ISSUE THREAD

**Issue by heiej** [SharpeRAD/Cake.Powershell#58]
I am trying to use the Cake.Powershell addin, but am running into some trouble.

Here is the output I am seeing
```
> .\build.ps1
Preparing to run build script...
Running build script...
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Powershell'.
```

I took a look at the Troubleshooting page, but it didn't seem to help https://github.com/SharpeRAD/Cake.Powershell/blob/master/TroubleShooting.md

Here is the top of my build.cake
```
#load nuget:?package=Cake.Core&version=0.27.1
#tool nuget:?package=NUnit.ConsoleRunner&version=3.8.0
#addin nuget:?package=Cake.Powershell&version=0.4.5
```

**Comment by SharpeRAD** [comment]
- Why are you referencing Cake.Core in your build script? 
- What version of "Cake.exe" are you running?

**Comment by heiej** [comment]
Ah, we were mistaken on how to pin the cake version. We were in fact on an old Cake.exe version. We are removing the reference to Cake.Core and have updated cake in our packagaes.config. Thanks for the help! Closing.
