### ISSUE TITLE
Recommended changes resulting from automated audit

### ISSUE THREAD

**Issue by Jericho** [SharpeRAD/Cake.Powershell#59]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [ ] You are currently referencing Cake.Core 0.26.0. Please upgrade to 0.28.0
- [ ] The Cake.Core reference should be private. Specifically, your addin's `.csproj` should have a line similar to this: `<PackageReference Include="Cake.Core" Version="0.28.0" PrivateAssets="All" />`
- [ ] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by SharpeRAD** [comment]
Resolve in v0.4.6
