### ISSUE TITLE
The published 0.4.8 NuGet package hasn't got Cake.Core in dependencies

### ISSUE THREAD

**Issue by marcinsmialek** [SharpeRAD/Cake.Powershell#75]
The 0.4.8 version depends on Cake.Core, but the dependency info is missing from nupkg

https://github.com/SharpeRAD/Cake.Powershell/commit/3bdbf955085eca8bddf0f74dbf1e258caeabde8b#diff-23506e4f03e24e1f1e6ef1d118c89178

**Comment by SharpeRAD** [comment]
While I appreciate that Nuget spec recommends adding references to all dependencies, Cake does not. They even created a bot to [pick up on this](https://github.com/cake-contrib/Cake.AddinDiscoverer).
