### ISSUE TITLE
Update to Cake 1.0.0.

### ISSUE THREAD

**Issue by azchohfi** [SharpeRAD/Cake.Powershell#81]
I'm getting a warning when using this on Cake 1.0.0.

This addin should be updated to Cake 1.0.0.

**Comment by SharpeRAD** [comment]
Agreed but probably going to need some help with that one as the existing dependencies aren't `.netstandard` compatible. Happy to accept a PR for this.

**Comment by azchohfi** [comment]
I'll send the PR.
I've updated everything accordingly and the only thing that is still not updated is Cake.FileHelpers. Still, using the latest available version did build everything just fine, and tests passed.

Once this is merged, we should be fine:
https://github.com/cake-contrib/Cake.FileHelpers/pull/34

Which .netstandard dependencies are you talking about?

**Comment by ldrick** [comment]
This unfortunately prevents from using 'dotnet cake' as suggested in cake documentation and using the cake build plugin in Azure DevOps pipelines.
